### ISSUE TITLE
How to incorporate a forked tree-sitter parser

### ISSUE THREAD

**Issue by KevOrr** [github/semantic#231]
Hi, recently I've ran into many issues with [tree-sitter/tree-sitter-php](https://github.com/tree-sitter/tree-sitter-php). I have a large PR waiting to be reviewed (https://github.com/tree-sitter/tree-sitter-php/pull/38). Unfortunately, I'm not sure the repo is being maintained anymore. Since I'm blocked on this, how can a forked version of one of the tree-sitter parsers be incorporated into (a local version of) Semantic?

**Comment by patrickt** [comment]
Firstly, my apologies for the delay in reviewing that PHP PR! I’ve pinged @maxbrunsfeld about squashing those CI errors; the patch looks good otherwise.

Until this PR lands easiest thing to do is to do what I’m doing in [this branch](https://github.com/github/semantic/pull/227/files): vendor a fork of tree-sitter-haskell and point that fork’s tree-sitter-php submodule at your fork. This isn’t great ergonomics, for which I apologize; I appreciate your patience and will get your PHP PR in as soon as possible.

**Comment by KevOrr** [comment]
No problem, like I said it's a large PR. You guys are doing awesome stuff
