### ISSUE TITLE
C# Tree sitter required?

### ISSUE THREAD

**Issue by HurricanKai** [github/semantic#375]
Regarding #156 
Looking through what has to be done to add C# support to this project, I'd like to ask if it is absolutely necessary to build a separate Tree Sitter here. The C# compiler Roslyn was made specifically to open up the compiler and give anyone access to every level of it's understanding of the code. In addition to the (hopefully) smaller work required (C# is quite a complex language after all) once done, the code would stay up-to-date forever.

**Comment by patrickt** [comment]
Hi there. We field this question, or varieties of it, a lot, and it’s fair: there does exist significant programming language tooling outside of Semantic that could help us in our aims. 

But ultimately, as was discussed in [this issue](https://github.com/github/semantic/issues/165), we’re not interested in tying our analysis techniques to the capabilities of a given language’s compiler, toolset, or even a single version of the language itself: we want Semantic to be a tool for cross-language abstract interpretation of _any_ programming language. As such, we’re willing to forgo the immediate productivity gains yielded by tying Semantic to third-party compilers in exchange for the long-term conceptual unity and clarity that an approach with `tree-sitter` as the lingua franca gains. In addition, tying Semantic’s capabilities to third-party compilers and suites turns a difficult problem into a problem that is both difficult and distributed; abstract interpretation is difficult enough without having to worry about asynchronicity, RPC, managing long-running daemons, interfacing with brittle and rapidly-shifting vendor APIs and tooling, etc. 

We’re currently engaged in a full-scale effort to reduce the activation energy required to bring new languages under the Semantic fold, and we’re doing so by leaning into, rather than away from, the `tree-sitter` suite: we now generate Haskell data types from tree-sitter grammar definitions directly, and are using these generated data types to sidestep swaths of inherent and incidental complexity. As such, contributing to the [tree-sitter C#](https://github.com/tree-sitter/tree-sitter-c-sharp) grammar will be the fastest way to move C# support forward. 

I’m going to close this issue out in favor of #156.
