### ISSUE TITLE
PHP: dynamic member lookup fails precise parsing

### ISSUE THREAD

**Issue by patrickt** [github/semantic#566]
The following code parses fine with `tree-sitter parse`, but fails with `semantic parse`:
```php
<?php
$this->{'any'};
?>
```

I’m unclear as to why this might be the case. (We end up in perishing in the guts of `GUnmarshalProduct`, where it’s expecting one and getting three nodes.)

The relevant tree-sitter dump:

```
(program [0, 0] - [3, 0]
  (php_tag [0, 0] - [0, 5])
  (expression_statement [1, 0] - [1, 18]
    (member_call_expression [1, 0] - [1, 17]
      object: (variable_name [1, 0] - [1, 5]
        (name [1, 1] - [1, 5]))
      name: (string [1, 8] - [1, 14])
      arguments: (arguments [1, 15] - [1, 17])))
  (text_interpolation [2, 0] - [2, 2]))
```

**Comment by maxbrunsfeld** [comment]
I think there are two bugs in `tree-sitter-php` that play into this:
* The `name` field is applied wrong in the grammar,
* Given the way that the `name` field is applied, `node-types.json` has been generated wrong.

In the `member_call_expression` rule, [the `name` field is associated](https://github.com/tree-sitter/tree-sitter-php/blob/df34d590a71e6a8d60dd45d446bf06aa19bbdcb4/grammar.js#L943) with the `_member_name` child, which is inlined, and can [contain three children](https://github.com/tree-sitter/tree-sitter-php/blob/df34d590a71e6a8d60dd45d446bf06aa19bbdcb4/grammar.js#L953): `{`, `_expression`, `}`.

That means that in this example, the `{` and `}` nodes will have the `name` field too, in addition to the `'any'` string, which was not intentional. But given this structure, [this `multiple` flag](https://github.com/tree-sitter/tree-sitter-php/blob/df34d590a71e6a8d60dd45d446bf06aa19bbdcb4/src/node-types.json#L1953) in the `node-types.json` should be `true`, not `false`.
