### ISSUE TITLE
When do you plan to support C++ and Rust?

### ISSUE THREAD

**Issue by flajann2** [github/semantic#572]
Or, how hard would it be for someone to implement it and do a pull request?

**Comment by patrickt** [comment]
We have tickets open for Rust support (which is in a considerable state of progress): https://github.com/github/semantic/issues/130

And C/C++ (though support for these is difficult, due to preprocessor directives and macros): https://github.com/github/semantic/issues/154

Documentation about how language support works can be found in the `docs/` folder.

I’m gonna close this out for now, but feel free to leave further comments in this thread or a new issue.
