### ISSUE TITLE
Python Bindings

### ISSUE THREAD

**Issue by bdrodes** [github/semantic#617]
Is there a way to easily ingest and manipulate a semantic AST in python? I realize I can walk the json generated by semantic, but I was hoping there was mechanism to modify/insert nodes into an existing semantic-produced AST through a python API.

**Comment by patrickt** [comment]
We don’t have any plans to provide APIs in languages other than Haskell, due to the time and effort associated with maintaining binding quality, and the fact that we’re focused on writing new analyses these days. It’s possible that a bindings tool like [hyphen](https://github.com/tbarnetlamb/hyphen) might help you, though I haven’t used it and can’t speak to its quality.
