### ISSUE TITLE
How to generate a call graph

### ISSUE THREAD

**Issue by codeanit** [github/semantic#646]
Dear Semantic Community Members,

I would like to know if anyone has generated a call graph
from the output of Semantic?

I am not sure if it was right for me to raise the issue here
or not but I believe that if any examples exists then it would
help others like me find more real use-cases of the tool
in general.

If the question is inappropriate, kindly close the issue.

Thank you.

**Comment by patrickt** [comment]
Right now we don’t have any extant examples of this; we used to, but that was in the days when we used the untyped AST. I think the best thing to do is to look at how the tagging analysis is done ([here](https://github.com/github/semantic/blob/master/semantic-java/src/Language/Java/Tags.hs) is the Java example) and repurpose that to emit nodes in your call graph rather than `Tag` data. I’m going to close this now, but feel free to leave comments if you have questions.
