### ISSUE TITLE
Question about future of this project

### ISSUE THREAD

**Issue by KevinHock** [github/semantic#647]
Hi All, this is an amazing project, 👍🏼  

I noticed it hasn't been updated in a while, perhaps the Semmle acquisition affected this project in some way.

Is this repo still going to be worked on for the long-term?

**Comment by dcreager** [comment]
Hi @KevinHock, thanks for the kind words!  It's true that we have not been doing much in this repository recently, though it has nothing to do with the Semmle acquisition.  As you might know, semantic builds on the [tree-sitter](https://tree-sitter.github.io/tree-sitter/) parsing library, adding more advanced program analysis functionality.  Awhile back, we added a [query language](https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries) to tree-sitter.  With that change, there are more Code Productivity features that we can implement purely using tree-sitter, without having to bring in the extra sophistication of semantic.  Code Navigation is one of those features, and is what our team has been spending most of our time on for the past year or so.

So, in short, it's just a question of our team's product focus. Right now we're working on features that can be implemented purely in tree-sitter, and so that's where we're spending most of our time. If/when we move on to product features that require abstract interpretation, or other deep forms of semantic analysis, our focus will shift back.

In the meantime, the repository remains public and open-source, so others are free to continue using it and extending it.

**Comment by KevinHock** [comment]
Thanks a bunch @dcreager :) That makes sense -- I appreciate the insight.

_gonna go ahead and close this issue_

**Comment by erickadalberto** [comment]
#634
