### ISSUE TITLE
Extract variables form a python code

### ISSUE THREAD

**Issue by raffaelepojer** [github/semantic#674]
Hi all! 
I'm currently trying to extract all variables and parameters arguments from a python code with semantic.

Ex: given some python code, I need to extract _variable1_, _variable2_, _arg1_ and _arg2_
```
def function(self, arg1, arg2):
    variable1 = something... 
    variable2 = something... 
```

By looking at some examples with [ast](https://docs.python.org/3/library/ast.html) of Python, the code for doing that can be something like that: 

```
root = AstLib.parse(code)
for node in AstLib.walk(root):
    if (isinstance(node, AstLib.Name) and isinstance(node.ctx, AstLib.Store)):
        varList.append(node.id)
    elif isinstance(node, AstLib.FunctionDef):
        for arg in node.args.args:
            varList.append(arg.arg)
```

Does anyone know how to do it by looking at the graph produced by semantic? 
Thanks

**Comment by patrickt** [comment]
Hi there. Right now Semantic’s tree structure is a bit user-unfriendly (since we’re designing an alternate representation, we haven’t sanded all the rough edges off the current one). If possible, I would recommend checking out `tree-sitter` and its associated query language. Such an operation should be a fairly simple query; you can find the docs here: https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries

The way to do it in Haskell would be to use `uniplate` and `syb` to write a generic top-down function, and use the cast operation from `Typeable` for your `isinstance` checks. I think we should keep this open and provide `Plated` instances for the types, at least until we integrate the higher-kinded approach and (possibly?) recover some way of doing recursion schemes

**Comment by raffaelepojer** [comment]
Thanks @patrickt for the quick response and the detailed answer, I will check tree-sitter
