### ISSUE TITLE
Investigate feasibility of switching to proto-lens for protobuf serialization.

### ISSUE THREAD

**Issue by patrickt** [github/semantic#89]
For historical reasons, we depend on forked versions of `proto3-suite` and `proto3-wire`. It would be pretty ideal if we could switch to `proto-lens`, given its somewhat nicer API and the fact that we don’t use any gRPC features that `proto3-suite` provides.

**Comment by patrickt** [comment]
Obviously, we can’t break backwards compatibility here, so it needs to be done very carefully.

**Comment by jkachmar** [comment]
Relevant modules from `proto-lens` as they relate to RPC service declaration:
- [`Service` types and classes](https://github.com/google/proto-lens/blob/0cb384a09810b4d512a432106e7a9602d2e2e7a6/proto-lens/src/Data/ProtoLens/Service/Types.hs)
- [Example `.proto` file with different RPC types](https://github.com/google/proto-lens/blob/0cb384a09810b4d512a432106e7a9602d2e2e7a6/proto-lens-tests/tests/service.proto)
- [Test demonstrating the types generated from the aforementioned `.proto` file](https://github.com/google/proto-lens/blob/0cb384a09810b4d512a432106e7a9602d2e2e7a6/proto-lens/src/Data/ProtoLens/Service/Types.hs)

Since `proto-lens` provides a `protoc` plugin you may be able to use that directly instead of however the `proto3-suite` stuff gets generated.

From there, I _imagine_ there’s enough information to generate any actual implementation code wiring those RPC definitions up to server/client handlers with `TemplateHaskell` or Generic derivation (to potentially avoid having to write more `protoc` stuff).
